### PR TITLE
Examples update

### PR DESCRIPTION
**Pull request by shakram02**
### Some updates for examples

- Convert some of the old examples to the new API
- Add some alphanumeric prefixes to python files that are inspired by the old examples and slightly related to the complexity of the topic
- Add header comments on the example
- Update the `README` of the examples so it becomes more attractive

### List of changes

- **added** `02_uniforms_and_attributes.py`, `03_alpha_blending.py`, `05_perspective_projection.py`, `07_multiple_instance_rendering.py`
- **changed** `README.md`

### CODE REVIEW

**Comment by shakram02** [comment]
I think it might be nice for the main `README to have some images of the rendered output

**Comment by cprogrammer1994** [comment]
fixes #133

**Comment by cprogrammer1994** [comment]
Thank you for the great work!

**Comment by shakram02** [comment]
you're welcome :+1:

**Pull request merged**
