### PR TITLE
create index array rendering example

### PR DESCRIPTION
**Pull request by shakram02**
### Description

As an absolute beginner in OpenGL I needed to create an index array drawing, I kept searching through the old and new examples and got it working, I thought that it's a nice to add for someone who'll use the library for the first time.

### Changes

- **added** `examples/index_array_render.py`

### CODE REVIEW

**Comment by cprogrammer1994** [comment]
Nice work!

**Comment by cprogrammer1994** [comment]
You can add yourself to the [Contributors](https://github.com/cprogrammer1994/ModernGL/blob/master/README.md#contributors) as well.

**Comment by shakram02** [comment]
Thanks, I guess I should add myself when I contribute to the core library, right now I'm just a noob :grimacing:

**Comment by cprogrammer1994** [comment]
All the contribution counts. 😄

**Pull request merged**
