### PR TITLE
Sampler object support

### PR DESCRIPTION
**Pull request by einarf**
### Description

* Support sampler objects.
* Allow disabling compare mode for samplers and depth textures
* Added missing context attributes ``max_samples``, ``max_integer_samples``, ``max_texture_units``, ``default_texture_unit``
* Added ``max_anisotropy`` attribute to context
* Added anisotropy attributes to textures
* TextureArray did not set all attributes on creation + missing docs
* Documenatation
* ``compare_mode`` can be disabled for depth textures

### CODE REVIEW

**Comment by einarf** [comment]
Done for now until someone looks at it

**Comment by cprogrammer1994** [comment]
#198

**Comment by einarf** [comment]
hmm. Maybe also add anisotropic filtering to all texture parameters as well? It's a shame not supporting it there as well.

**Comment by cprogrammer1994** [comment]
> Maybe also add anisotropic filtering to all texture parameters as well?

Sure let's support it there too.

---

Changes look fine.
I see no methods that could be undefined for OpenGL 3.3 (compatible with old hw ✓)
I see no non-backward-compatible changes ✓

I want to try them before merging. Are you using them already?

**Comment by einarf** [comment]
I'm using them yes. I can try to make my example available. I've been using a minecraft scene for testing.

**Comment by einarf** [comment]
I'm also seeing the need for clearing the sampler binding on a texture unit. The sampler will actually be bound to the texture unit and not the texture itself. This might cause a lot of confusion.

**Comment by einarf** [comment]
You can play with in demosys-py:

* Clone https://github.com/Contraz/demosys-py and check out ``samplers`` branch
* Create and activate a virtualenv
* python setup.py develop
* ``pip install https://github.com/einarf/PyWavefront/archive/binary-cache.zip``
* with moderngl: ``python setup.py develop``

Run the effect:
```
python manage.py runeffect examples.minecraft
```

I'm messing just toggling sampler states based on time in the draw loop:

https://github.com/Contraz/demosys-py/blob/66ede7df0ac228025ce7d5af2d6d056e43bae97b/examples/minecraft/effect.py#L37-L42

**Comment by einarf** [comment]
I revived TextureArray as well enabling the docs and fixing some initialization issues. I use the feature and it's working perfectly fine as far as I can see.

**Comment by einarf** [comment]
Think I should stop here before it gets out of hand 😄

**Comment by einarf** [comment]
Got a rough estimate when the next release is planned for? I just need to plan what order I merge branches in my own projects. Not in a hurry.

**Comment by cprogrammer1994** [comment]
I plan to do most of the changes from my side this week.

**Comment by cprogrammer1994** [comment]
Thank you!

**Pull request merged**
