### PR TITLE
Missing details in docs

### PR DESCRIPTION
**Pull request by einarf**
### Description

Add a lot more info to the context, texture and sampler docs. When starting with moderngl I basically had to read the source or look at examples to understand things fully.

This is also a great way for me to learn the details.

### CODE REVIEW

**Comment by einarf** [comment]
I thought about also adding more info to texture parameters since some of the can be somewhat a mystery unless you know the ropes.

**Comment by einarf** [comment]
If you think the texture docs are decent I can copy this around in the different texture classes.

**Comment by cprogrammer1994** [comment]
Looks great!

Changes on texture docs are good too, you can add them to the other texture classes.

**Comment by einarf** [comment]
I think that was it for now. I'm sure there's more that can be improved. I'll try to prepare another batch of updates when I find things.

**Comment by cprogrammer1994** [comment]
Thank you! I merge this now. It will be part of the release. :)

**Comment by cprogrammer1994** [comment]
The docs improvements are available here: https://moderngl.readthedocs.io/en/latest/
I will make a release on Monday or earlier, depends on how I succeed with the glBlendEquation sketch.

**Comment by einarf** [comment]
Awesome.

I thought about adding ``GL_TEXTURE_BORDER_COLOR``, ``GL_TEXTURE_WRAP_R``, ``GL_TEXTURE_MIN_LOD`` and ``GL_TEXTURE_MAX_LOD`` to Sampler before release to make the feature 100% complete.

I can probably get that done right now, but if that's too close to release for your taste we can wait.

**Pull request merged**
