### PR TITLE
Broke up moderngl.__init__.py into modules.

### PR DESCRIPTION
**Pull request by NeilGirdhar**
Made setup.py executable.
Removed unused imports.
Addresses https://github.com/cprogrammer1994/ModernGL/issues/200

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
@cprogrammer1994 Could you help me fix this error?  I can' figure out what's happening.

**Comment by einarf** [comment]
You changed the signature for ``Context.clear`` and ``Framebuffer.clear`` slightly using float ``0.0`` instead of ``0`` so they no longer match with the documentation. ``test_documentation`` inspects each method documented.

Just modify the rst files and run ``pytest`` locally to verify.

**Comment by NeilGirdhar** [comment]
@einarf Thanks for looking at it.  The problem is my regular expression match was catching the floating point constants, so I changed it to `attribute_access = re.compile(r"[a-zA-Z]\w*\.(\w+)")`, which worked.

Do you have any idea how to make it so that I'm not testing against the installed `moderngl`?  My `test_local` is failing.

**Comment by einarf** [comment]
I usually just ``python setup.py develop`` in a virtualenv since I'm always on latest master.

**Comment by NeilGirdhar** [comment]
Thanks!! I forgot about `develop`!

**Comment by NeilGirdhar** [comment]
@cprogrammer1994 Did you have a chance to take a look at this?

**Comment by einarf** [comment]
I'll wait with my PRs until this one is resolved.

**Comment by NeilGirdhar** [comment]
@einarf Awesome, thank you.

**Comment by cprogrammer1994** [comment]
Hi! I have tried this one and works fine even with py 3.4 I will merge this for sure. I have 3 things to merge.

- this one
- getting fbo.read work with depth attachment
- the fix-integer-rgba-rbos branch

**Comment by einarf** [comment]
Great. I have quite a few small things here and there to commit and need to rebase.

**Comment by cprogrammer1994** [comment]
I have fully tested this.
Thank you for the contribution! merging...

**Pull request merged**
