### PR TITLE
VertexArray index element size can be INT, SHORT and BYTE

### PR DESCRIPTION
**Pull request by einarf**
### Description

Support `UNSIGNED_INT`, `UNSIGNED_SHORT` and `UNSIGNED_BYTE` index buffers in VertexArray.
Added an optional `index_element_size` parameter (default: 4) were users can specify this. It can be 1, 2 or 4.

### CODE REVIEW

**Comment by einarf** [comment]
Failed on docs and might want to make a test or two..

**Comment by einarf** [comment]
All done. Was a few more small commits due it pycharm messing up tabs/spaces in C files. Think I will use VS Code for projects like this in the future.

**Comment by cprogrammer1994** [comment]
Sorry for the different indentation in py & cpp files. I was using spaces for python and tabs for c++.
I will run the tests today and merge.
Thank you!

**Comment by einarf** [comment]
Nothing wrong with the indentation. It was my tools failing me.

Also, it would be nice to see a new release when this is merged :)

**Comment by einarf** [comment]
You might want to squash this PR to remove all these spammy indentation commits 😄

**Comment by einarf** [comment]
Just for inspiration: `VC.gltf` from gltf sample library with mixed 8, 16 bit index buffers.

**Comment by cprogrammer1994** [comment]
Wow 😄

**Comment by cprogrammer1994** [comment]
> Also, it would be nice to see a new release when this is merged :)

Released: [ModernGL 5.3.0](https://pypi.org/project/ModernGL/5.3.0/)

**Comment by einarf** [comment]
Thanks ❤️

**Pull request merged**
