### PR TITLE
Example windows (Completed)

### PR DESCRIPTION
**Pull request by einarf**
Examples using ModernGL with pyqt5, pyglet, glfw and sdl2

Each window type support the folloing features:

* Runtime resizing and viewport update
* Fullscreen mode
* Multisample antialiasing (MSAA) default at 4
* Keyboard events
* Mouse position and button events
* Vsync toggle
* Toggle mouse cursor on or off

Events are passed from the window to an example class in a platform and framework-indenpedent way.

## Example Options

```
optional arguments:
  -h, --help            show this help message and exit
  -w {glfw,pyglet,pyqt5,sdl2}, --window {glfw,pyglet,pyqt5,sdl2}
                        Name for the window type to use
  -fs, --fullscreen     Open the window in fullscreen mode
  -vs VSYNC, --vsync VSYNC
                        Enable or disable vsync
  -s SAMPLES, --samples SAMPLES
                        Specify the desired number of samples to use for
                        multisampling
  -c CURSOR, --cursor CURSOR
                        Enable or disable displaying the mouse cursor
```

For example:

```bash
# Run example in fullscreen with 8 x MSAA, vsync and no visible mouse cursor
python 03_alpha_blending.py --fullscreen --samples 8 --cursor off --vsync on

# Run example using SDL2
python 03_alpha_blending.py --window sdl2

# Run example using pyglet
python 03_alpha_blending.py --window pyglet

# Run example using glfw
python 03_alpha_blending.py --window glfw
```

## Example Template

```py
from window import Example, run_example


class MyExample(Example):
    # The minimum required OpenGL version (default 3.3)
    gl_version = (3, 3)
    # Title of the window
    title = "Empty Window"
    # Size of the window to open
    window_size = (1280, 720)
    # Lock aspect ratio letting the window class automatically
    # calculate the right viewport regardless of window size.
    # This can add black borders because the viewport is centered
    # vertically and horizontally.
    aspect_ratio = 16 / 9
    # Should users be able to resize the window?
    resizable = True

    def __init__(self, **kwargs):
        # ctx and wnd are mainly passed in there
        super().__init__(**kwargs)

        # The ModernGL context is avaialble
        # self.ctx.something()

        # A window reference is also availabel
        # self.wnd.size

    def render(self, time: float, frame_time: float):
        """
        Called every frame

        Params:
            time (float): Number of seconds elapsed since rendering started
            frame_time (float): Seconds since last frame
        """
        self.ctx.clear(0.2, 0.4, 0.7)
        # Render stuff here

    def key_event(self, key, action):
        """
        Handle key events in a generic way supporting all window types.
        wnd.keys references key constant for the selected window type.
        """
        if action == self.wnd.keys.ACTION_PRESS:
            if key == self.wnd.keys.SPACE:
                print("Space was pressed")

        if action == self.wnd.keys.ACTION_RELEASE:
            if key == self.wnd.keys.SPACE:
                print("Space was released")

    def mouse_position_event(self, x, y):
        """
        Mouse position reported in pixel position
        with the upper left corner as the origin
        """
        print("Mouse pos", x, y)

    def mouse_press_event(self, x, y, button):
        """Reports left and right mouse button presses + position"""
        if button == 1:
            print("Left mouse button pressed @", x, y)
        if button == 2:
            print("Right mouse button pressed @", x, y)

    def mouse_release_event(self, x, y, button):
        """Reports left and right mouse button releases + position"""
        if button == 1:
            print("Left mouse button released @", x, y)
        if button == 2:
            print("Right mouse button released @", x, y)


# Make the module importable so this example
# can be used by other examples!
if __name__ == '__main__':
    run_example(MyExample)
```

### CODE REVIEW

**Comment by einarf** [comment]
Maybe this is a decent direction. It's somewhat similar to what I have done in demosys-py. All examples can run using a specified window class (with a sane default).

```
python 01_b_simple_color_triangle --window glfw --vsync on --samples 4
(... more params)
```

Should make it fairly easy to port over all the basic window properies such as:

* Window size (+actual buffer size to handle 4k and retina displays)
* Multisampling
* Double buffering
* Specify OpenGL version exactly using core contexts
* Vsync
* Fullscreen
* Resizing
* Toggle mouse corsor on/off
* Fixed aspect ratio and auto-caluclation of viewport on resize
* Custom window title

**Comment by einarf** [comment]
Will try to get this one done during the weekend

**Comment by einarf** [comment]
Viewport obeys the configured aspect ratio doing vertical and horisontal centering. All windows can do fullscreen and support run-time resizing.

Ultra Wide 21:9 3440 x 1440
uw_example

Smaller window with resized height.
viewport_height

**Comment by einarf** [comment]
Managed to get pretty far.

Remaining tasks:

* Link window examples from README
* Proper README for the window examples
* Update examples README with parameters and usage
* Support mouse buttons click events
* Possibly include the camera from #276 
* Add SDL2 window
* Add pyglet window
* Covert remaining examples

**Comment by cprogrammer1994** [comment]
I have run it on window.

image

looks great :)

**Comment by einarf** [comment]
I think this is ready for merge now. This was a lot more work than I originally planned for 😄

**Comment by cprogrammer1994** [comment]
merged :)

**Pull request merged**
